### ISSUE TITLE
Add indexOf method for arrays as well

### ISSUE THREAD

**Issue by talha-asad** [xamfoo/reactive-obj#11]
I see you have most of the array functions implemented, however one readOnly one seems to be missing `indexOf`. Will you accept a PR for this?

**Comment by xamfoo** [comment]
Non-mutating methods on arrays can be accessed like this:

``` javascript
var x = new ReactiveObj(❴ a: ['foo', 'bar'] });
var a = x.get('a');

a.indexOf('foo'); // returns 0
a.indexOf('bar'); // returns 1
```

I'm not sure about adding support for `x.indexOf('a', 'foo')` because it seems unnecessary.

**Comment by talha-asad** [comment]
If you are to remove an item from an array at a specific index, the general pattern of  `arr.splice(arr.indexOf(item), 1)` is not usable because indexOf is not a function. But it is doable by using a get once and then just mutating the array.

At times i have seen a bit of delay in the time i mutate a deeply nested key and the time it takes to reflect that change on the view layer. How are mutations tracked internally? Is it a timer or do you use Tracker for that?

**Comment by xamfoo** [comment]
An alternative without mutating the array.

``` javascript
var x = new ReactiveObj({ a: ['foo', 'bar'] });

x.update('a', (arr) => arr.filter((v) => v !== 'foo'));
```

No timers. The reactive object stores references to reactive computations (`Tracker.autorun()`) and invalidates them when values are changed. The performance can be affected by reactive computations themselves. In this case, does using `ReactiveVar` or `ReactiveDict` improve performance?
