### ISSUE TITLE
How to get all data of the object?

### ISSUE THREAD

**Issue by thearabbit** [xamfoo/reactive-obj#8]
I have like this

``` js
var x = new ReactiveObj();
x.set('a', 'A'); 
x.set('b', 'B'); 
x.set('c', 'C'); 
```

I can get one property by `x.get('a')`;
But now I want to get all of data.

``` js
{
   {a: 'A'},
   {b: 'B'},
   {c: 'C'}
}
```

please help me.

**Comment by xamfoo** [comment]
`x.get([])` should give you the root node.

**Comment by thearabbit** [comment]
Thanks, should be clear on `readme`.
